name: social_foundation_em
description: A new Flutter plugin project.
version: 0.1.11
homepage: https://github.com/gohopo/social_foundation_em
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  social_foundation:
    git:
      url: https://github.com/gohopo/social_foundation.git
    # path: ../../gohopo/social_foundation/
  im_flutter_sdk:
    git:
      url: "https://github.com/easemob/im_flutter_sdk_oh.git"
      ref: "main"

flutter:
  plugin:
    platforms:
      android:
        package: com.gohopo.social_foundation_em
        pluginClass: SocialFoundationEmPlugin
      ios:
        pluginClass: SocialFoundationEmPlugin
